let lang_ru = {
    "title": "Красивый мир аттракторов",
    "nav_info": "Информация",
    "nav_more_articles": "Больше информации",
    "nav_gallery": "Галерея",
    "nav_up": "Наверх",
    "click_to_visit": "Нажми, чтобы посетить",
    "implementation_paragraph": "Take about 1 000 00 points, scatter them randomly on your simulation square, iterate each of the points using some attarctor equations(for example Lorenz), at each iteration add some constant value to an intensity map at each point's coordinate. Do about a million iterations. You will get an intensity map that can be converted to color map.",
    "visual_representation": "Визуальное представление полиномного аттрактора",
    "what_are_attractors": "Что такое аттракторы?",
    "implementation": "Имплементация",
    "usefull_info": "Полезная информация про аттракторы",
    "interractive_site": "Интеррактивный сайт, где можно поиграться с аттракторами",
    "polynomial_site": "Сайт с полиномными аттракторами",
    "german_site": "Немецкий сайт с разными аттракторами",
    "wikipedia_site": "Страница на вики про аттракторы",
    "other_attractors_site": "Есть ли другие хаотические аттракторы?",
    "programming_lorenz_site": "Программирование аттрактора Леренца",
    "chaos_theory_site": "Теория хаоса(визуализация аттракторов)",
    "more_images": "Больше картинок аттракторов",
    "footer_sources":"Исходники",
    "footer_other_projects":"Больше проектов",
    "footer_email":"Написать на почту",
    "footer_vk":"Написать в ВК",
    "footer_youtube":"Ютуб канал"
};